[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit ADS1X15 @ 2.5.0
    adafruit/RTClib @ 2.1.4
    bblanchon/ArduinoJson @ 7.3.0
    esp32async/ESPAsyncWebServer @ 3.7.1
    esp32async/AsyncTCP @ 3.3.5
    knolleary/PubSubClient @ 2.8
    milesburton/DallasTemperature @ 3.9.1
    paulstoffregen/OneWire @ 2.3.8
